version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/mautic
    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: wget --output-document=mautic.tar.gz https://github.com/mautic/mautic/archive/2.12.1.tar.gz && tar -xzf mautic.tar.gz
      - run: cp MauticRecaptchaBundle/ mautic/plugins/
